#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2017
- Ubuntu

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
  - cd src
  - dotnet restore

build_script:
  - sh: sudo apt-get update -y && apt-get -y install cmake build-essential libssl-dev pkg-config libboost-all-dev libsodium-dev libzmq5
  - cd MiningCore
  - dotnet publish -c Release --framework netcoreapp2.1
  - cd ../MiningCore.Tests
  - dotnet build -c Release --framework netcoreapp2.1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests again only selected assemblies and/or categories
test_script:
 - dotnet test -c Release --no-build

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Webhook
  - provider: Webhook
    url: https://registry.hub.docker.com/u/coinfoundry/miningcore-docker/trigger/5cea19ab-b489-4f7c-9fb2-da4112c51e66/
    on_build_success: true
    on_build_failure: false
